# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=200)),
                ('director_name', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('music_by', models.CharField(max_length=200)),
                ('cast', models.CharField(max_length=200)),
                ('runtime', models.IntegerField()),
                ('release_date', models.DateTimeField()),
                ('budget', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
